<?php

$classPath = t3lib_extMgm::extPath('flux', 'Classes/');
return array(
	'tx_flux_viewhelpers_flexformviewhelper' => $classPath . "ViewHelpers/FlexformViewHelper.php",
	'tx_flux_viewhelpers_widget_gridviewhelper' => $classPath . "ViewHelpers/Widget/GridViewHelper.php",
	'tx_flux_viewhelpers_widget_controller_gridcontroller' => $classPath . "ViewHelpers/Widget/Controller/GridController.php",
	'tx_flux_viewhelpers_flexform_field_abstractfieldviewhelper' => $classPath . "ViewHelpers/Flexform/Field/AbstractFieldViewHelper.php",
	'tx_flux_viewhelpers_flexform_field_checkboxviewhelper' => $classPath . "ViewHelpers/Flexform/Field/CheckboxViewHelper.php",
	'tx_flux_viewhelpers_flexform_field_groupviewhelper' => $classPath . "ViewHelpers/Flexform/Field/GroupViewHelper.php",
	'tx_flux_viewhelpers_flexform_field_inputviewhelper' => $classPath . "ViewHelpers/Flexform/Field/InputViewHelper.php",
	'tx_flux_viewhelpers_flexform_field_selectviewhelper' => $classPath . "ViewHelpers/Flexform/Field/SelectViewHelper.php",
	'tx_flux_viewhelpers_flexform_field_textviewhelper' => $classPath . "ViewHelpers/Flexform/Field/TextViewHelper.php",
	'tx_flux_viewhelpers_flexform_field_treeviewhelper' => $classPath . "ViewHelpers/Flexform/Field/TreeViewHelper.php",
	'tx_flux_viewhelpers_flexform_field_userfuncviewhelper' => $classPath . "ViewHelpers/Flexform/Field/UserFuncViewHelper.php",
	'tx_flux_viewhelpers_flexform_grid_columnviewhelper' => $classPath . "ViewHelpers/Flexform/Grid/ColumnViewHelper.php",
	'tx_flux_viewhelpers_flexform_grid_rowviewhelper' => $classPath . "ViewHelpers/Flexform/Grid/RowViewHelper.php",
	'tx_flux_viewhelpers_flexform_gridviewhelper' => $classPath . "ViewHelpers/Flexform/GridViewHelper.php",
	'tx_flux_viewhelpers_flexform_renderfieldviewhelper' => $classPath . "ViewHelpers/Flexform/RenderFieldViewHelper.php",
	'tx_flux_viewhelpers_flexform_sheetviewhelper' => $classPath . "ViewHelpers/Flexform/SheetViewHelper.php",
	'tx_flux_userfunction_errorreporter' => $classPath . "UserFunction/ErrorReporter.php",
	'tx_flux_userfunction_nofields' => $classPath . "UserFunction/NoFields.php",
	'tx_flux_provider_abstractconfigurationprovider' => $classPath . "Provider/AbstractConfigurationProvider.php",
	'tx_flux_provider_abstractcontentobjectconfigurationprovider' => $classPath . "Provider/AbstractContentObjectConfigurationProvider.php",
	'tx_flux_provider_abstractpluginconfigurationprovider' => $classPath . "Provider/AbstractPluginConfigurationProvider.php",
	'tx_flux_provider_configurationproviderinterface' => $classPath . "Provider/ConfigurationProviderInterface.php",
	'tx_flux_provider_configurationservice' => $classPath . "Provider/ConfigurationService.php",
	'tx_flux_provider_contentobjectconfigurationproviderinterface' => $classPath . "Provider/ContentObjectConfigurationProviderInterface.php",
	'tx_flux_provider_pluginconfigurationproviderinterface' => $classPath . "Provider/PluginConfigurationProviderInterface.php",
	'tx_flux_provider_configuration_fallback_configurationprovider' => $classPath . "Provider/Configuration/Fallback/ConfigurationProvider.php",
	'tx_flux_provider_configuration_fallback_contentobjectconfigurationprovider' => $classPath . "Provider/Configuration/Fallback/ContentObjectConfigurationProvider.php",
	'tx_flux_provider_configuration_fallback_pluginconfigurationprovider' => $classPath . "Provider/Configuration/Fallback/PluginConfigurationProvider.php",
	'tx_flux_service_flexform' => $classPath . "Service/FlexForm.php",
	'tx_flux_service_grid' => $classPath . "Service/Grid.php",
	'tx_flux_service_json' => $classPath . "Service/Json.php",
	'tx_flux_mvc_view_exposedstandaloneview' => $classPath . "MVC/View/ExposedStandaloneView.php",
	'tx_flux_mvc_view_exposedtemplateview' => $classPath . "MVC/View/ExposedTemplateView.php",
	'tx_flux_core_viewhelper_abstractflexformviewhelper' => $classPath . "Core/ViewHelper/AbstractFlexformViewHelper.php",
	'tx_flux_controller_fluxcontroller' => $classPath . "Controller/FluxController.php",
	'tx_flux_configuration_configurationmanager' => $classPath . "Configuration/ConfigurationManager.php",
	'tx_flux_backend_dynamicflexform' => $classPath . "Backend/DynamicFlexForm.php",
	'tx_flux_backend_preview' => $classPath . "Backend/Preview.php",
	'tx_flux_backend_templavoilapreview' => $classPath . "Backend/TemplaVoilaPreview.php",
	'tx_flux_core' => $classPath . "Core.php",
);

?>