<?php
return array(
	'Tx_Flux_Core' => 'FluidTYPO3\Flux\Core',
	'Tx_Flux_Form' => 'FluidTYPO3\Flux\Form',
	'Tx_Flux_Backend_DynamicFlexForm' => 'FluidTYPO3\Flux\Backend\DynamicFlexForm',
	'Tx_Flux_Backend_Preview' => 'FluidTYPO3\Flux\Backend\Preview',
	'Tx_Flux_Backend_TceMain' => 'FluidTYPO3\Flux\Backend\TceMain',
	'Tx_Flux_Backend_TableConfigurationPostProcessor' => 'FluidTYPO3\Flux\Backend\TableConfigurationPostProcessor',
	'Tx_Flux_Backend_TypoScriptTemplate' => 'FluidTYPO3\Flux\Backend\TypoScriptTemplate',
	'Tx_Flux_Controller_AbstractFluxController' => 'FluidTYPO3\Flux\Controller\AbstractFluxController',
	'Tx_Flux_Form_AbstractFormComponent' => 'FluidTYPO3\Flux\Form\AbstractFormComponent',
	'Tx_Flux_Form_AbstractFormContainer' => 'FluidTYPO3\Flux\Form\AbstractFormContainer',
	'Tx_Flux_Form_AbstractFormField' => 'FluidTYPO3\Flux\Form\AbstractFormField',
	'Tx_Flux_Form_AbstractInlineFormField' => 'FluidTYPO3\Flux\Form\AbstractInlineFormField',
	'Tx_Flux_Form_AbstractMultiValueFormField' => 'FluidTYPO3\Flux\Form\AbstractMultiValueFormField',
	'Tx_Flux_Form_AbstractRelationFormField' => 'FluidTYPO3\Flux\Form\AbstractRelationFormField',
	'Tx_Flux_Form_AbstractWizard' => 'FluidTYPO3\Flux\Form\AbstractWizard',
	'Tx_Flux_Form_ContainerInterface' => 'FluidTYPO3\Flux\Form\ContainerInterface',
	'Tx_Flux_Form_FieldContainerInterface' => 'FluidTYPO3\Flux\Form\FieldContainerInterface',
	'Tx_Flux_Form_FieldInterface' => 'FluidTYPO3\Flux\Form\FieldInterface',
	'Tx_Flux_Form_FormInterface' => 'FluidTYPO3\Flux\Form\FormInterface',
	'Tx_Flux_Form_RelationFieldInterface' => 'FluidTYPO3\Flux\Form\RelationFieldInterface',
	'Tx_Flux_Form_WizardInterface' => 'FluidTYPO3\Flux\Form\WizardInterface',
	'Tx_Flux_Form_Container_Column' => 'FluidTYPO3\Flux\Form\Container\Column',
	'Tx_Flux_Form_Container_Container' => 'FluidTYPO3\Flux\Form\Container\Container',
	'Tx_Flux_Form_Container_Content' => 'FluidTYPO3\Flux\Form\Container\Content',
	'Tx_Flux_Form_Container_Grid' => 'FluidTYPO3\Flux\Form\Container\Grid',
	'Tx_Flux_Form_Container_Object' => 'FluidTYPO3\Flux\Form\Container\Object',
	'Tx_Flux_Form_Container_Row' => 'FluidTYPO3\Flux\Form\Container\Row',
	'Tx_Flux_Form_Container_Section' => 'FluidTYPO3\Flux\Form\Container\Section',
	'Tx_Flux_Form_Container_Sheet' => 'FluidTYPO3\Flux\Form\Container\Sheet',
	'Tx_Flux_Form_Field_Inline_Fal' => 'FluidTYPO3\Flux\Form\Field\Inline\Fal',
	'Tx_Flux_Form_Field_Checkbox' => 'FluidTYPO3\Flux\Form\Field\Checkbox',
	'Tx_Flux_Form_Field_ControllerActions' => 'FluidTYPO3\Flux\Form\Field\ControllerActions',
	'Tx_Flux_Form_Field_Custom' => 'FluidTYPO3\Flux\Form\Field\Custom',
	'Tx_Flux_Form_Field_DateTime' => 'FluidTYPO3\Flux\Form\Field\DateTime',
	'Tx_Flux_Form_Field_File' => 'FluidTYPO3\Flux\Form\Field\File',
	'Tx_Flux_Form_Field_Flex' => 'FluidTYPO3\Flux\Form\Field\Flex',
	'Tx_Flux_Form_Field_Inline' => 'FluidTYPO3\Flux\Form\Field\Inline',
	'Tx_Flux_Form_Field_Input' => 'FluidTYPO3\Flux\Form\Field\Input',
	'Tx_Flux_Form_Field_Passthrough' => 'FluidTYPO3\Flux\Form\Field\Passthrough',
	'Tx_Flux_Form_Field_Relation' => 'FluidTYPO3\Flux\Form\Field\Relation',
	'Tx_Flux_Form_Field_Select' => 'FluidTYPO3\Flux\Form\Field\Select',
	'Tx_Flux_Form_Field_Text' => 'FluidTYPO3\Flux\Form\Field\Text',
	'Tx_Flux_Form_Field_Tree' => 'FluidTYPO3\Flux\Form\Field\Tree',
	'Tx_Flux_Form_Field_UserFunction' => 'FluidTYPO3\Flux\Form\Field\UserFunction',
	'Tx_Flux_Form_Wizard_Add' => 'FluidTYPO3\Flux\Form\Wizard\Add',
	'Tx_Flux_Form_Wizard_ColorPicker' => 'FluidTYPO3\Flux\Form\Wizard\ColorPicker',
	'Tx_Flux_Form_Wizard_Edit' => 'FluidTYPO3\Flux\Form\Wizard\Edit',
	'Tx_Flux_Form_Wizard_Link' => 'FluidTYPO3\Flux\Form\Wizard\Link',
	'Tx_Flux_Form_Wizard_List' => 'FluidTYPO3\Flux\Form\Wizard\ListWizard',
	'Tx_Flux_Form_Wizard_ListWizard' => 'FluidTYPO3\Flux\Form\Wizard\ListWizard',
	'Tx_Flux_Form_Wizard_Select' => 'FluidTYPO3\Flux\Form\Wizard\Select',
	'Tx_Flux_Form_Wizard_Slider' => 'FluidTYPO3\Flux\Form\Wizard\Slider',
	'Tx_Flux_Form_Wizard_Suggest' => 'FluidTYPO3\Flux\Form\Wizard\Suggest',
	'Tx_Flux_Provider_AbstractProvider' => 'FluidTYPO3\Flux\Provider\AbstractProvider',
	'Tx_Flux_Provider_ContentProvider' => 'FluidTYPO3\Flux\Provider\ContentProvider',
	'Tx_Flux_Provider_ProviderInterface' => 'FluidTYPO3\Flux\Provider\ProviderInterface',
	'Tx_Flux_Provider_Provider' => 'FluidTYPO3\Flux\Provider\Provider',
	'Tx_Flux_Service_ContentService' => 'FluidTYPO3\Flux\Service\ContentService',
	'Tx_Flux_Service_FluxService' => 'FluidTYPO3\Flux\Service\FluxService',
	'Tx_Flux_Service_LanguageFileService' => 'FluidTYPO3\Flux\Service\LanguageFileService',
	'Tx_Flux_View_ExposedTemplateView' => 'FluidTYPO3\Flux\View\ExposedTemplateView',
	'Tx_Flux_ViewHelpers_Be_ContentAreaViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Be\ContentAreaViewHelper',
	'Tx_Flux_ViewHelpers_Be_ContentElementViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Be\ContentElementViewHelper',
	'Tx_Flux_ViewHelpers_Be_Link_Content_NewViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Be\Link\Content\NewViewHelper',
	'Tx_Flux_ViewHelpers_Be_Link_Content_PasteViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Be\Link\Content\PasteViewHelper',
	'Tx_Flux_ViewHelpers_Content_GetViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Content\GetViewHelper',
	'Tx_Flux_ViewHelpers_Content_RenderViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Content\RenderViewHelper',
	'Tx_Flux_ViewHelpers_IsCollapsedViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\IsCollapsedViewHelper',
	'Tx_Flux_ViewHelpers_VariableViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\VariableViewHelper',
	'Tx_Flux_ViewHelpers_Widget_GridViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Widget\GridViewHelper',
	'Tx_Flux_ViewHelpers_Widget_Controller_GridController' => 'FluidTYPO3\Flux\ViewHelpers\Widget\Controller\GridController',

	// old legacy aliases, Provider pattern simplification - class files have been removed
	'Tx_Flux_Provider_AbstractConfigurationProvider' => 'FluidTYPO3\Flux\Provider\AbstractProvider',
	'Tx_Flux_Provider_AbstractContentObjectConfigurationProvider' => 'FluidTYPO3\Flux\Provider\AbstractProvider',
	'Tx_Flux_Provider_AbstractPluginConfigurationProvider' => 'FluidTYPO3\Flux\Provider\AbstractProvider',
	'Tx_Flux_Provider_Fallback_FallbackConfigurationProvider' => 'FluidTYPO3\Flux\Provider\Provider',
	'Tx_Flux_Provider_Fallback_FallbackContentObjectConfigurationProvider' => 'FluidTYPO3\Flux\Provider\Provider',
	'Tx_Flux_Provider_Fallback_FallbackPluginConfigurationProvider' => 'FluidTYPO3\Flux\Provider\Provider',
	'Tx_Flux_Provider_ConfigurationProviderInterface' => 'FluidTYPO3\Flux\Provider\ProviderInterface',
	'Tx_Flux_Provider_ContentObjectConfigurationProviderInterface' => 'FluidTYPO3\Flux\Provider\ProviderInterface',

	// very old legacy alias, flux:flexform.renderContent -> flux:content.render
	'FluidTYPO3\Flux\ViewHelpers\Flexform\RenderContentViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Content\RenderViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_RenderContentViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Content\RenderViewHelper',

	// consistency alias for invalid resolved name of class "List" in Form\Wizard scope to be used as "list" rather than "listWizard"
	'FluidTYPO3\Flux\Form\Wizard\List' => 'FluidTYPO3\Flux\Form\Wizard\ListWizard',

	// class renames post-namespace change, Utility classes
	'FluidTYPO3\Flux\Utility\Annotation' => 'FluidTYPO3\Flux\Utility\AnnotationUtility',
	'Tx_Flux_Utility_Annotation' => 'FluidTYPO3\Flux\Utility\AnnotationUtility',
	'FluidTYPO3\Flux\Utility\ClipBoard' => 'FluidTYPO3\Flux\Utility\ClipBoardUtility',
	'Tx_Flux_Utility_ClipBoard' => 'FluidTYPO3\Flux\Utility\ClipBoardUtility',
	'FluidTYPO3\Flux\Utility\Miscellaneous' => 'FluidTYPO3\Flux\Utility\MiscellaneousUtility',
	'Tx_Flux_Utility_Miscellaneous' => 'FluidTYPO3\Flux\Utility\MiscellaneousUtility',
	'FluidTYPO3\Flux\Utility\Path' => 'FluidTYPO3\Flux\Utility\PathUtility',
	'Tx_Flux_Utility_Path' => 'FluidTYPO3\Flux\Utility\PathUtility',
	'FluidTYPO3\Flux\Utility\RecursiveArray' => 'FluidTYPO3\Flux\Utility\RecursiveArrayUtility',
	'Tx_Flux_Utility_RecursiveArray' => 'FluidTYPO3\Flux\Utility\RecursiveArrayUtility',
	'FluidTYPO3\Flux\Utility\Resolve' => 'FluidTYPO3\Flux\Utility\ResolveUtility',
	'Tx_Flux_Utility_Resolve' => 'FluidTYPO3\Flux\Utility\ResolveUtility',
	'FluidTYPO3\Flux\Utility\Version' => 'FluidTYPO3\Flux\Utility\VersionUtility',
	'Tx_Flux_Utility_Version' => 'FluidTYPO3\Flux\Utility\VersionUtility',

	// class renames post-namespace change, ViewHelper API simplification
	'FluidTYPO3\Flux\ViewHelpers\AbstractFlexformViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\AbstractFormViewHelper',
	'Tx_Flux_ViewHelpers_AbstractFlexformViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\AbstractFormViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\FlexformViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\FormViewHelper',
	'Tx_Flux_ViewHelpers_FlexformViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\FormViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\GridViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\GridViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_GridViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\GridViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Grid\ColumnViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Grid\ColumnViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Grid_ColumnViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Grid\ColumnViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Grid\RowViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Grid\RowViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Grid_RowViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Grid\RowViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\ContainerViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\ContainerViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_ContainerViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\ContainerViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\DataViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\DataViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_DataViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\DataViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\ObjectViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\ObjectViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_ObjectViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\ObjectViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\SectionViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\SectionViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_SectionViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\SectionViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\SheetViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\SheetViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_SheetViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\SheetViewHelper',

	'Tx_Flux_ViewHelpers_Flexform_Field_AbstractFieldViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\AbstractFieldViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_AbstractRelationFieldViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\AbstractRelationFieldViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_AbstractMultiValueFieldViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\AbstractMultiValueFieldViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_AbstractInlineFieldViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\AbstractInlineFieldViewHelper',

	'Tx_Flux_ViewHelpers_Flexform_Field_CheckboxViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\CheckboxViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\CheckboxViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\CheckboxViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_ControllerActionsViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\ControllerActionsViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\ControllerActionsViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\ControllerActionsViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_CustomViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\CustomViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\CustomViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\CustomViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_FileViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\FileViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\FileViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\FileViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_InlineViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\InlineViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\InlineViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\InlineViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_InputViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\InputViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\InputViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\InputViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_RelationViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\RelationViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\RelationViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\RelationViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_SelectViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\SelectViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\SelectViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\SelectViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_TextViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\TextViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\TextViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\TextViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_TreeViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\TreeViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\TreeViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\TreeViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_UserFuncViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\UserFuncViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\UserFuncViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Field\UserFuncViewHelper',

	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\AbstractWizardViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\AbstractWizardViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_AbstractWizardViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\AbstractWizardViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\AddViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\AddViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_AddViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\AddViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\ColorPickerViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\ColorPickerViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_ColorPickerViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\ColorPickerViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\EditViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\EditViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_EditViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\EditViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\LinkViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\LinkViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_LinkViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\LinkViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\ListViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\ListViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_ListViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\ListViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\SelectViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\SelectViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_SelectViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\SelectViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\SliderViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\SliderViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_SliderViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\SliderViewHelper',
	'FluidTYPO3\Flux\ViewHelpers\Flexform\Field\Wizard\SuggestViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\SuggestViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_Field_Wizard_SuggestViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Wizard\SuggestViewHelper',

	// saving you for last, foul vestigal organ! Grid/ColumnViewHelper will replace you.
	'FluidTYPO3\Flux\ViewHelpers\Flexform\ContentViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\ContentViewHelper',
	'Tx_Flux_ViewHelpers_Flexform_ContentViewHelper' => 'FluidTYPO3\Flux\ViewHelpers\Form\ContentViewHelper',
);
